apiVersion: v1
kind: ConfigMap
metadata:
  name: diki-options
  namespace: kube-system
data:
  disa-kubernetes-stig: ""
  disa-kubernetes-stig-rules: |
    - ruleID: "242417"
      args:
        acceptedPods:
        - labelSelector:
            matchLabels:
              k8s-app: kube-dns
          namespaceLabelSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          justification: "coredns is a system component and not a user pod."
        - labelSelector:
            matchLabels:
              app.kubernetes.io/name: diki-operator
          namespaceLabelSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          justification: "diki-operator is a system component and not a user pod."
        - labelSelector:
            matchLabels:
              app.kubernetes.io/name: diki
          namespaceLabelSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          justification: "diki scanner jobs are system components and not user pods."
        - labelSelector:
            matchLabels:
              app: kindnet
          namespaceLabelSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          justification: "kindnet is a system component and not a user pod."
        - labelSelector:
            matchLabels:
              component: etcd
          namespaceLabelSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          justification: "etcd is a system component and not a user pod."
  security-hardened-k8s-rules: |
    - ruleID: "2000"
      args:
        acceptedNamespaces:
        - labelSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          justification: "kube-system namespace is accepted to allow traffic by default."
          acceptedTraffic:
            ingress: true
            egress: true
    - ruleID: "2001"
      args:
        acceptedPods:
        - labelSelector:
            matchLabels:
              component: etcd
          namespaceLabelSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          justification: "etcd is accepted to allow privilege escalation."
        - labelSelector:
            matchLabels:
              app: kindnet
          namespaceLabelSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          justification: "kindnet is accepted to allow privilege escalation."
    - ruleID: "2008"
      args:
        acceptedPods:
        - labelSelector:
            matchLabels:
              component: etcd
          namespaceLabelSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          justification: "etcd requires host path volumes for data and certificates."
          volumeNames:
          - "etcd-certs"
          - "etcd-data"
        - labelSelector:
            matchLabels:
              app: kindnet
          namespaceLabelSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          justification: "kindnet requires host path volumes for CNI configuration and networking."
          volumeNames:
          - "cni-cfg"
          - "xtables-lock"
          - "lib-modules"
          - "nri-plugin"
