# SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: exporter.diki.gardener.cloud/v1alpha1
kind: DikiExporterConfiguration

reportPath: ./example/report.json
complianceScanName: example-compliancescan

outputs:
- type: ConfigMap
  name: diki-report-
  config:
    namespace: kube-system
    namePrefix: diki-report-
    labels:
      app: diki-exporter
