apiVersion: exporter.diki.gardener.cloud/v1alpha1
kind: ReportExporterConfiguration

reportPath: ./example/report.json
complianceScanName: example-compliancescan
waitForReport: true
reportWaitTimeout: 10m

outputs:
- type: ConfigMap
  name: compliance-scan-report
  config:
    namespace: kube-system
    namePrefix: compliance-scan-report-
- type: Webhook
  name: example-webhook-output
  config:
    url: "https://compliance-api.corp.example.com/v1/reports"
    method: POST
    headersFile: /creds/headers.json
    tls:
      caCertFile: /creds/ca.crt
      clientCertFile: /creds/client.crt
      clientKeyFile: /creds/client.key
