//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by defaulter-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// RegisterDefaults adds defaulters functions to the given scheme.
// Public to allow building arbitrary schemes.
// All generated defaulters are covering - they call all nested defaulters.
func RegisterDefaults(scheme *runtime.Scheme) error {
	scheme.AddTypeDefaultingFunc(&DikiOperatorConfiguration{}, func(obj interface{}) { SetObjectDefaults_DikiOperatorConfiguration(obj.(*DikiOperatorConfiguration)) })
	return nil
}

func SetObjectDefaults_DikiOperatorConfiguration(in *DikiOperatorConfiguration) {
	SetDefaults_DikiOperatorConfiguration(in)
	SetDefaults_Log(&in.Log)
	if in.LeaderElection != nil {
		SetDefaults_LeaderElectionConfiguration(in.LeaderElection)
	}
	SetDefaults_ComplianceScanConfig(&in.Controllers.ComplianceScan)
	SetDefaults_DikiRunnerConfig(&in.Controllers.ComplianceScan.DikiRunner)
	SetDefaults_ServerConfiguration(&in.Server)
	SetDefaults_HTTPSServer(&in.Server.Webhooks)
	SetDefaults_Server(&in.Server.Webhooks.Server)
	SetDefaults_TLS(&in.Server.Webhooks.TLS)
	if in.Server.HealthProbes != nil {
		SetDefaults_Server(in.Server.HealthProbes)
	}
	if in.Server.Metrics != nil {
		SetDefaults_Server(in.Server.Metrics)
	}
}
