# SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "name" . }}
  namespace: {{ (.Release.Namespace)  }}
webhooks:
- name: compliancescan.validation.gardener.cloud
  admissionReviewVersions: ["v1", "v1beta1"]
  timeoutSeconds: 10
  rules:
  - apiGroups:
    - "diki.gardener.cloud"
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - compliancescans
  failurePolicy: Fail
  clientConfig:
  # TODO (georgibaltiev): revisit this configuration once the diki-operator starts being invoked out-of-cluster
  {{- if .Values.webhookConfig.urlHostname }}
    url: {{ printf "https://%s:443/webhooks/compliancescan" (.Values.webhookConfig.urlHostname) }}
  {{- else }}
    service:
      name: {{ include "name" . }}
      namespace: {{ .Release.Namespace }}
      path: /webhooks/compliancescan
      port: 443
  {{- end }}
    caBundle: {{ required ".Values.webhookConfig.tls.caBundle is required" (b64enc .Values.webhookConfig.tls.caBundle) }}
  sideEffects: None