//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	diki "github.com/gardener/diki-operator/pkg/apis/diki"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*ComplianceRun)(nil), (*diki.ComplianceRun)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ComplianceRun_To_diki_ComplianceRun(a.(*ComplianceRun), b.(*diki.ComplianceRun), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*diki.ComplianceRun)(nil), (*ComplianceRun)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_diki_ComplianceRun_To_v1alpha1_ComplianceRun(a.(*diki.ComplianceRun), b.(*ComplianceRun), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ComplianceRunList)(nil), (*diki.ComplianceRunList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ComplianceRunList_To_diki_ComplianceRunList(a.(*ComplianceRunList), b.(*diki.ComplianceRunList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*diki.ComplianceRunList)(nil), (*ComplianceRunList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_diki_ComplianceRunList_To_v1alpha1_ComplianceRunList(a.(*diki.ComplianceRunList), b.(*ComplianceRunList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ComplianceRunSpec)(nil), (*diki.ComplianceRunSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ComplianceRunSpec_To_diki_ComplianceRunSpec(a.(*ComplianceRunSpec), b.(*diki.ComplianceRunSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*diki.ComplianceRunSpec)(nil), (*ComplianceRunSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_diki_ComplianceRunSpec_To_v1alpha1_ComplianceRunSpec(a.(*diki.ComplianceRunSpec), b.(*ComplianceRunSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ComplianceRunStatus)(nil), (*diki.ComplianceRunStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ComplianceRunStatus_To_diki_ComplianceRunStatus(a.(*ComplianceRunStatus), b.(*diki.ComplianceRunStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*diki.ComplianceRunStatus)(nil), (*ComplianceRunStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_diki_ComplianceRunStatus_To_v1alpha1_ComplianceRunStatus(a.(*diki.ComplianceRunStatus), b.(*ComplianceRunStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Condition)(nil), (*diki.Condition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Condition_To_diki_Condition(a.(*Condition), b.(*diki.Condition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*diki.Condition)(nil), (*Condition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_diki_Condition_To_v1alpha1_Condition(a.(*diki.Condition), b.(*Condition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Findings)(nil), (*diki.Findings)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Findings_To_diki_Findings(a.(*Findings), b.(*diki.Findings), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*diki.Findings)(nil), (*Findings)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_diki_Findings_To_v1alpha1_Findings(a.(*diki.Findings), b.(*Findings), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Rule)(nil), (*diki.Rule)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Rule_To_diki_Rule(a.(*Rule), b.(*diki.Rule), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*diki.Rule)(nil), (*Rule)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_diki_Rule_To_v1alpha1_Rule(a.(*diki.Rule), b.(*Rule), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RuleOptionsConfigMapRef)(nil), (*diki.RuleOptionsConfigMapRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RuleOptionsConfigMapRef_To_diki_RuleOptionsConfigMapRef(a.(*RuleOptionsConfigMapRef), b.(*diki.RuleOptionsConfigMapRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*diki.RuleOptionsConfigMapRef)(nil), (*RuleOptionsConfigMapRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_diki_RuleOptionsConfigMapRef_To_v1alpha1_RuleOptionsConfigMapRef(a.(*diki.RuleOptionsConfigMapRef), b.(*RuleOptionsConfigMapRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RulesetConfig)(nil), (*diki.RulesetConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RulesetConfig_To_diki_RulesetConfig(a.(*RulesetConfig), b.(*diki.RulesetConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*diki.RulesetConfig)(nil), (*RulesetConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_diki_RulesetConfig_To_v1alpha1_RulesetConfig(a.(*diki.RulesetConfig), b.(*RulesetConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RulesetSummary)(nil), (*diki.RulesetSummary)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RulesetSummary_To_diki_RulesetSummary(a.(*RulesetSummary), b.(*diki.RulesetSummary), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*diki.RulesetSummary)(nil), (*RulesetSummary)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_diki_RulesetSummary_To_v1alpha1_RulesetSummary(a.(*diki.RulesetSummary), b.(*RulesetSummary), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Summary)(nil), (*diki.Summary)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Summary_To_diki_Summary(a.(*Summary), b.(*diki.Summary), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*diki.Summary)(nil), (*Summary)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_diki_Summary_To_v1alpha1_Summary(a.(*diki.Summary), b.(*Summary), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_ComplianceRun_To_diki_ComplianceRun(in *ComplianceRun, out *diki.ComplianceRun, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ComplianceRunSpec_To_diki_ComplianceRunSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ComplianceRunStatus_To_diki_ComplianceRunStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ComplianceRun_To_diki_ComplianceRun is an autogenerated conversion function.
func Convert_v1alpha1_ComplianceRun_To_diki_ComplianceRun(in *ComplianceRun, out *diki.ComplianceRun, s conversion.Scope) error {
	return autoConvert_v1alpha1_ComplianceRun_To_diki_ComplianceRun(in, out, s)
}

func autoConvert_diki_ComplianceRun_To_v1alpha1_ComplianceRun(in *diki.ComplianceRun, out *ComplianceRun, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_diki_ComplianceRunSpec_To_v1alpha1_ComplianceRunSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_diki_ComplianceRunStatus_To_v1alpha1_ComplianceRunStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_diki_ComplianceRun_To_v1alpha1_ComplianceRun is an autogenerated conversion function.
func Convert_diki_ComplianceRun_To_v1alpha1_ComplianceRun(in *diki.ComplianceRun, out *ComplianceRun, s conversion.Scope) error {
	return autoConvert_diki_ComplianceRun_To_v1alpha1_ComplianceRun(in, out, s)
}

func autoConvert_v1alpha1_ComplianceRunList_To_diki_ComplianceRunList(in *ComplianceRunList, out *diki.ComplianceRunList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]diki.ComplianceRun)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_ComplianceRunList_To_diki_ComplianceRunList is an autogenerated conversion function.
func Convert_v1alpha1_ComplianceRunList_To_diki_ComplianceRunList(in *ComplianceRunList, out *diki.ComplianceRunList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ComplianceRunList_To_diki_ComplianceRunList(in, out, s)
}

func autoConvert_diki_ComplianceRunList_To_v1alpha1_ComplianceRunList(in *diki.ComplianceRunList, out *ComplianceRunList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]ComplianceRun)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_diki_ComplianceRunList_To_v1alpha1_ComplianceRunList is an autogenerated conversion function.
func Convert_diki_ComplianceRunList_To_v1alpha1_ComplianceRunList(in *diki.ComplianceRunList, out *ComplianceRunList, s conversion.Scope) error {
	return autoConvert_diki_ComplianceRunList_To_v1alpha1_ComplianceRunList(in, out, s)
}

func autoConvert_v1alpha1_ComplianceRunSpec_To_diki_ComplianceRunSpec(in *ComplianceRunSpec, out *diki.ComplianceRunSpec, s conversion.Scope) error {
	out.Rulesets = *(*[]diki.RulesetConfig)(unsafe.Pointer(&in.Rulesets))
	return nil
}

// Convert_v1alpha1_ComplianceRunSpec_To_diki_ComplianceRunSpec is an autogenerated conversion function.
func Convert_v1alpha1_ComplianceRunSpec_To_diki_ComplianceRunSpec(in *ComplianceRunSpec, out *diki.ComplianceRunSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ComplianceRunSpec_To_diki_ComplianceRunSpec(in, out, s)
}

func autoConvert_diki_ComplianceRunSpec_To_v1alpha1_ComplianceRunSpec(in *diki.ComplianceRunSpec, out *ComplianceRunSpec, s conversion.Scope) error {
	out.Rulesets = *(*[]RulesetConfig)(unsafe.Pointer(&in.Rulesets))
	return nil
}

// Convert_diki_ComplianceRunSpec_To_v1alpha1_ComplianceRunSpec is an autogenerated conversion function.
func Convert_diki_ComplianceRunSpec_To_v1alpha1_ComplianceRunSpec(in *diki.ComplianceRunSpec, out *ComplianceRunSpec, s conversion.Scope) error {
	return autoConvert_diki_ComplianceRunSpec_To_v1alpha1_ComplianceRunSpec(in, out, s)
}

func autoConvert_v1alpha1_ComplianceRunStatus_To_diki_ComplianceRunStatus(in *ComplianceRunStatus, out *diki.ComplianceRunStatus, s conversion.Scope) error {
	out.Conditions = *(*[]diki.Condition)(unsafe.Pointer(&in.Conditions))
	out.Phase = diki.ComplianceRunPhase(in.Phase)
	out.Rulesets = *(*[]diki.RulesetSummary)(unsafe.Pointer(&in.Rulesets))
	return nil
}

// Convert_v1alpha1_ComplianceRunStatus_To_diki_ComplianceRunStatus is an autogenerated conversion function.
func Convert_v1alpha1_ComplianceRunStatus_To_diki_ComplianceRunStatus(in *ComplianceRunStatus, out *diki.ComplianceRunStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_ComplianceRunStatus_To_diki_ComplianceRunStatus(in, out, s)
}

func autoConvert_diki_ComplianceRunStatus_To_v1alpha1_ComplianceRunStatus(in *diki.ComplianceRunStatus, out *ComplianceRunStatus, s conversion.Scope) error {
	out.Conditions = *(*[]Condition)(unsafe.Pointer(&in.Conditions))
	out.Phase = ComplianceRunPhase(in.Phase)
	out.Rulesets = *(*[]RulesetSummary)(unsafe.Pointer(&in.Rulesets))
	return nil
}

// Convert_diki_ComplianceRunStatus_To_v1alpha1_ComplianceRunStatus is an autogenerated conversion function.
func Convert_diki_ComplianceRunStatus_To_v1alpha1_ComplianceRunStatus(in *diki.ComplianceRunStatus, out *ComplianceRunStatus, s conversion.Scope) error {
	return autoConvert_diki_ComplianceRunStatus_To_v1alpha1_ComplianceRunStatus(in, out, s)
}

func autoConvert_v1alpha1_Condition_To_diki_Condition(in *Condition, out *diki.Condition, s conversion.Scope) error {
	out.Type = diki.ConditionType(in.Type)
	out.Status = diki.ConditionStatus(in.Status)
	out.LastUpdateTime = in.LastUpdateTime
	out.LastTransitionTime = in.LastTransitionTime
	out.Reason = in.Reason
	out.Message = in.Message
	return nil
}

// Convert_v1alpha1_Condition_To_diki_Condition is an autogenerated conversion function.
func Convert_v1alpha1_Condition_To_diki_Condition(in *Condition, out *diki.Condition, s conversion.Scope) error {
	return autoConvert_v1alpha1_Condition_To_diki_Condition(in, out, s)
}

func autoConvert_diki_Condition_To_v1alpha1_Condition(in *diki.Condition, out *Condition, s conversion.Scope) error {
	out.Type = ConditionType(in.Type)
	out.Status = ConditionStatus(in.Status)
	out.LastUpdateTime = in.LastUpdateTime
	out.LastTransitionTime = in.LastTransitionTime
	out.Reason = in.Reason
	out.Message = in.Message
	return nil
}

// Convert_diki_Condition_To_v1alpha1_Condition is an autogenerated conversion function.
func Convert_diki_Condition_To_v1alpha1_Condition(in *diki.Condition, out *Condition, s conversion.Scope) error {
	return autoConvert_diki_Condition_To_v1alpha1_Condition(in, out, s)
}

func autoConvert_v1alpha1_Findings_To_diki_Findings(in *Findings, out *diki.Findings, s conversion.Scope) error {
	out.Failed = *(*[]diki.Rule)(unsafe.Pointer(&in.Failed))
	out.Errored = *(*[]diki.Rule)(unsafe.Pointer(&in.Errored))
	out.Warning = *(*[]diki.Rule)(unsafe.Pointer(&in.Warning))
	return nil
}

// Convert_v1alpha1_Findings_To_diki_Findings is an autogenerated conversion function.
func Convert_v1alpha1_Findings_To_diki_Findings(in *Findings, out *diki.Findings, s conversion.Scope) error {
	return autoConvert_v1alpha1_Findings_To_diki_Findings(in, out, s)
}

func autoConvert_diki_Findings_To_v1alpha1_Findings(in *diki.Findings, out *Findings, s conversion.Scope) error {
	out.Failed = *(*[]Rule)(unsafe.Pointer(&in.Failed))
	out.Errored = *(*[]Rule)(unsafe.Pointer(&in.Errored))
	out.Warning = *(*[]Rule)(unsafe.Pointer(&in.Warning))
	return nil
}

// Convert_diki_Findings_To_v1alpha1_Findings is an autogenerated conversion function.
func Convert_diki_Findings_To_v1alpha1_Findings(in *diki.Findings, out *Findings, s conversion.Scope) error {
	return autoConvert_diki_Findings_To_v1alpha1_Findings(in, out, s)
}

func autoConvert_v1alpha1_Rule_To_diki_Rule(in *Rule, out *diki.Rule, s conversion.Scope) error {
	out.ID = in.ID
	out.Name = in.Name
	return nil
}

// Convert_v1alpha1_Rule_To_diki_Rule is an autogenerated conversion function.
func Convert_v1alpha1_Rule_To_diki_Rule(in *Rule, out *diki.Rule, s conversion.Scope) error {
	return autoConvert_v1alpha1_Rule_To_diki_Rule(in, out, s)
}

func autoConvert_diki_Rule_To_v1alpha1_Rule(in *diki.Rule, out *Rule, s conversion.Scope) error {
	out.ID = in.ID
	out.Name = in.Name
	return nil
}

// Convert_diki_Rule_To_v1alpha1_Rule is an autogenerated conversion function.
func Convert_diki_Rule_To_v1alpha1_Rule(in *diki.Rule, out *Rule, s conversion.Scope) error {
	return autoConvert_diki_Rule_To_v1alpha1_Rule(in, out, s)
}

func autoConvert_v1alpha1_RuleOptionsConfigMapRef_To_diki_RuleOptionsConfigMapRef(in *RuleOptionsConfigMapRef, out *diki.RuleOptionsConfigMapRef, s conversion.Scope) error {
	out.Name = in.Name
	out.Namespace = in.Namespace
	out.Key = (*string)(unsafe.Pointer(in.Key))
	return nil
}

// Convert_v1alpha1_RuleOptionsConfigMapRef_To_diki_RuleOptionsConfigMapRef is an autogenerated conversion function.
func Convert_v1alpha1_RuleOptionsConfigMapRef_To_diki_RuleOptionsConfigMapRef(in *RuleOptionsConfigMapRef, out *diki.RuleOptionsConfigMapRef, s conversion.Scope) error {
	return autoConvert_v1alpha1_RuleOptionsConfigMapRef_To_diki_RuleOptionsConfigMapRef(in, out, s)
}

func autoConvert_diki_RuleOptionsConfigMapRef_To_v1alpha1_RuleOptionsConfigMapRef(in *diki.RuleOptionsConfigMapRef, out *RuleOptionsConfigMapRef, s conversion.Scope) error {
	out.Name = in.Name
	out.Namespace = in.Namespace
	out.Key = (*string)(unsafe.Pointer(in.Key))
	return nil
}

// Convert_diki_RuleOptionsConfigMapRef_To_v1alpha1_RuleOptionsConfigMapRef is an autogenerated conversion function.
func Convert_diki_RuleOptionsConfigMapRef_To_v1alpha1_RuleOptionsConfigMapRef(in *diki.RuleOptionsConfigMapRef, out *RuleOptionsConfigMapRef, s conversion.Scope) error {
	return autoConvert_diki_RuleOptionsConfigMapRef_To_v1alpha1_RuleOptionsConfigMapRef(in, out, s)
}

func autoConvert_v1alpha1_RulesetConfig_To_diki_RulesetConfig(in *RulesetConfig, out *diki.RulesetConfig, s conversion.Scope) error {
	out.ID = in.ID
	out.Version = in.Version
	out.RuleOptionsConfigMapRef = (*diki.RuleOptionsConfigMapRef)(unsafe.Pointer(in.RuleOptionsConfigMapRef))
	return nil
}

// Convert_v1alpha1_RulesetConfig_To_diki_RulesetConfig is an autogenerated conversion function.
func Convert_v1alpha1_RulesetConfig_To_diki_RulesetConfig(in *RulesetConfig, out *diki.RulesetConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_RulesetConfig_To_diki_RulesetConfig(in, out, s)
}

func autoConvert_diki_RulesetConfig_To_v1alpha1_RulesetConfig(in *diki.RulesetConfig, out *RulesetConfig, s conversion.Scope) error {
	out.ID = in.ID
	out.Version = in.Version
	out.RuleOptionsConfigMapRef = (*RuleOptionsConfigMapRef)(unsafe.Pointer(in.RuleOptionsConfigMapRef))
	return nil
}

// Convert_diki_RulesetConfig_To_v1alpha1_RulesetConfig is an autogenerated conversion function.
func Convert_diki_RulesetConfig_To_v1alpha1_RulesetConfig(in *diki.RulesetConfig, out *RulesetConfig, s conversion.Scope) error {
	return autoConvert_diki_RulesetConfig_To_v1alpha1_RulesetConfig(in, out, s)
}

func autoConvert_v1alpha1_RulesetSummary_To_diki_RulesetSummary(in *RulesetSummary, out *diki.RulesetSummary, s conversion.Scope) error {
	out.ID = in.ID
	out.Version = in.Version
	if err := Convert_v1alpha1_Summary_To_diki_Summary(&in.Summary, &out.Summary, s); err != nil {
		return err
	}
	out.Findings = (*diki.Findings)(unsafe.Pointer(in.Findings))
	return nil
}

// Convert_v1alpha1_RulesetSummary_To_diki_RulesetSummary is an autogenerated conversion function.
func Convert_v1alpha1_RulesetSummary_To_diki_RulesetSummary(in *RulesetSummary, out *diki.RulesetSummary, s conversion.Scope) error {
	return autoConvert_v1alpha1_RulesetSummary_To_diki_RulesetSummary(in, out, s)
}

func autoConvert_diki_RulesetSummary_To_v1alpha1_RulesetSummary(in *diki.RulesetSummary, out *RulesetSummary, s conversion.Scope) error {
	out.ID = in.ID
	out.Version = in.Version
	if err := Convert_diki_Summary_To_v1alpha1_Summary(&in.Summary, &out.Summary, s); err != nil {
		return err
	}
	out.Findings = (*Findings)(unsafe.Pointer(in.Findings))
	return nil
}

// Convert_diki_RulesetSummary_To_v1alpha1_RulesetSummary is an autogenerated conversion function.
func Convert_diki_RulesetSummary_To_v1alpha1_RulesetSummary(in *diki.RulesetSummary, out *RulesetSummary, s conversion.Scope) error {
	return autoConvert_diki_RulesetSummary_To_v1alpha1_RulesetSummary(in, out, s)
}

func autoConvert_v1alpha1_Summary_To_diki_Summary(in *Summary, out *diki.Summary, s conversion.Scope) error {
	out.Passed = in.Passed
	out.Skipped = in.Skipped
	out.Accepted = in.Accepted
	out.Warning = in.Warning
	out.Failed = in.Failed
	out.Errored = in.Errored
	return nil
}

// Convert_v1alpha1_Summary_To_diki_Summary is an autogenerated conversion function.
func Convert_v1alpha1_Summary_To_diki_Summary(in *Summary, out *diki.Summary, s conversion.Scope) error {
	return autoConvert_v1alpha1_Summary_To_diki_Summary(in, out, s)
}

func autoConvert_diki_Summary_To_v1alpha1_Summary(in *diki.Summary, out *Summary, s conversion.Scope) error {
	out.Passed = in.Passed
	out.Skipped = in.Skipped
	out.Accepted = in.Accepted
	out.Warning = in.Warning
	out.Failed = in.Failed
	out.Errored = in.Errored
	return nil
}

// Convert_diki_Summary_To_v1alpha1_Summary is an autogenerated conversion function.
func Convert_diki_Summary_To_v1alpha1_Summary(in *diki.Summary, out *Summary, s conversion.Scope) error {
	return autoConvert_diki_Summary_To_v1alpha1_Summary(in, out, s)
}
