//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	diki "github.com/gardener/diki-operator/pkg/apis/diki"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*ComplianceRun)(nil), (*diki.ComplianceRun)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ComplianceRun_To_diki_ComplianceRun(a.(*ComplianceRun), b.(*diki.ComplianceRun), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*diki.ComplianceRun)(nil), (*ComplianceRun)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_diki_ComplianceRun_To_v1alpha1_ComplianceRun(a.(*diki.ComplianceRun), b.(*ComplianceRun), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ComplianceRunList)(nil), (*diki.ComplianceRunList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ComplianceRunList_To_diki_ComplianceRunList(a.(*ComplianceRunList), b.(*diki.ComplianceRunList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*diki.ComplianceRunList)(nil), (*ComplianceRunList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_diki_ComplianceRunList_To_v1alpha1_ComplianceRunList(a.(*diki.ComplianceRunList), b.(*ComplianceRunList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ComplianceRunSpec)(nil), (*diki.ComplianceRunSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ComplianceRunSpec_To_diki_ComplianceRunSpec(a.(*ComplianceRunSpec), b.(*diki.ComplianceRunSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*diki.ComplianceRunSpec)(nil), (*ComplianceRunSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_diki_ComplianceRunSpec_To_v1alpha1_ComplianceRunSpec(a.(*diki.ComplianceRunSpec), b.(*ComplianceRunSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ComplianceRunStatus)(nil), (*diki.ComplianceRunStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ComplianceRunStatus_To_diki_ComplianceRunStatus(a.(*ComplianceRunStatus), b.(*diki.ComplianceRunStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*diki.ComplianceRunStatus)(nil), (*ComplianceRunStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_diki_ComplianceRunStatus_To_v1alpha1_ComplianceRunStatus(a.(*diki.ComplianceRunStatus), b.(*ComplianceRunStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Condition)(nil), (*diki.Condition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Condition_To_diki_Condition(a.(*Condition), b.(*diki.Condition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*diki.Condition)(nil), (*Condition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_diki_Condition_To_v1alpha1_Condition(a.(*diki.Condition), b.(*Condition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Options)(nil), (*diki.Options)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Options_To_diki_Options(a.(*Options), b.(*diki.Options), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*diki.Options)(nil), (*Options)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_diki_Options_To_v1alpha1_Options(a.(*diki.Options), b.(*Options), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OptionsConfigMapRef)(nil), (*diki.OptionsConfigMapRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_OptionsConfigMapRef_To_diki_OptionsConfigMapRef(a.(*OptionsConfigMapRef), b.(*diki.OptionsConfigMapRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*diki.OptionsConfigMapRef)(nil), (*OptionsConfigMapRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_diki_OptionsConfigMapRef_To_v1alpha1_OptionsConfigMapRef(a.(*diki.OptionsConfigMapRef), b.(*OptionsConfigMapRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Rule)(nil), (*diki.Rule)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Rule_To_diki_Rule(a.(*Rule), b.(*diki.Rule), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*diki.Rule)(nil), (*Rule)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_diki_Rule_To_v1alpha1_Rule(a.(*diki.Rule), b.(*Rule), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RulesFindings)(nil), (*diki.RulesFindings)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RulesFindings_To_diki_RulesFindings(a.(*RulesFindings), b.(*diki.RulesFindings), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*diki.RulesFindings)(nil), (*RulesFindings)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_diki_RulesFindings_To_v1alpha1_RulesFindings(a.(*diki.RulesFindings), b.(*RulesFindings), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RulesResults)(nil), (*diki.RulesResults)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RulesResults_To_diki_RulesResults(a.(*RulesResults), b.(*diki.RulesResults), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*diki.RulesResults)(nil), (*RulesResults)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_diki_RulesResults_To_v1alpha1_RulesResults(a.(*diki.RulesResults), b.(*RulesResults), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RulesSummary)(nil), (*diki.RulesSummary)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RulesSummary_To_diki_RulesSummary(a.(*RulesSummary), b.(*diki.RulesSummary), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*diki.RulesSummary)(nil), (*RulesSummary)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_diki_RulesSummary_To_v1alpha1_RulesSummary(a.(*diki.RulesSummary), b.(*RulesSummary), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RulesetConfig)(nil), (*diki.RulesetConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RulesetConfig_To_diki_RulesetConfig(a.(*RulesetConfig), b.(*diki.RulesetConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*diki.RulesetConfig)(nil), (*RulesetConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_diki_RulesetConfig_To_v1alpha1_RulesetConfig(a.(*diki.RulesetConfig), b.(*RulesetConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RulesetOptions)(nil), (*diki.RulesetOptions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RulesetOptions_To_diki_RulesetOptions(a.(*RulesetOptions), b.(*diki.RulesetOptions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*diki.RulesetOptions)(nil), (*RulesetOptions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_diki_RulesetOptions_To_v1alpha1_RulesetOptions(a.(*diki.RulesetOptions), b.(*RulesetOptions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RulesetSummary)(nil), (*diki.RulesetSummary)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RulesetSummary_To_diki_RulesetSummary(a.(*RulesetSummary), b.(*diki.RulesetSummary), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*diki.RulesetSummary)(nil), (*RulesetSummary)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_diki_RulesetSummary_To_v1alpha1_RulesetSummary(a.(*diki.RulesetSummary), b.(*RulesetSummary), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_ComplianceRun_To_diki_ComplianceRun(in *ComplianceRun, out *diki.ComplianceRun, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ComplianceRunSpec_To_diki_ComplianceRunSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ComplianceRunStatus_To_diki_ComplianceRunStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ComplianceRun_To_diki_ComplianceRun is an autogenerated conversion function.
func Convert_v1alpha1_ComplianceRun_To_diki_ComplianceRun(in *ComplianceRun, out *diki.ComplianceRun, s conversion.Scope) error {
	return autoConvert_v1alpha1_ComplianceRun_To_diki_ComplianceRun(in, out, s)
}

func autoConvert_diki_ComplianceRun_To_v1alpha1_ComplianceRun(in *diki.ComplianceRun, out *ComplianceRun, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_diki_ComplianceRunSpec_To_v1alpha1_ComplianceRunSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_diki_ComplianceRunStatus_To_v1alpha1_ComplianceRunStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_diki_ComplianceRun_To_v1alpha1_ComplianceRun is an autogenerated conversion function.
func Convert_diki_ComplianceRun_To_v1alpha1_ComplianceRun(in *diki.ComplianceRun, out *ComplianceRun, s conversion.Scope) error {
	return autoConvert_diki_ComplianceRun_To_v1alpha1_ComplianceRun(in, out, s)
}

func autoConvert_v1alpha1_ComplianceRunList_To_diki_ComplianceRunList(in *ComplianceRunList, out *diki.ComplianceRunList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]diki.ComplianceRun)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_ComplianceRunList_To_diki_ComplianceRunList is an autogenerated conversion function.
func Convert_v1alpha1_ComplianceRunList_To_diki_ComplianceRunList(in *ComplianceRunList, out *diki.ComplianceRunList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ComplianceRunList_To_diki_ComplianceRunList(in, out, s)
}

func autoConvert_diki_ComplianceRunList_To_v1alpha1_ComplianceRunList(in *diki.ComplianceRunList, out *ComplianceRunList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]ComplianceRun)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_diki_ComplianceRunList_To_v1alpha1_ComplianceRunList is an autogenerated conversion function.
func Convert_diki_ComplianceRunList_To_v1alpha1_ComplianceRunList(in *diki.ComplianceRunList, out *ComplianceRunList, s conversion.Scope) error {
	return autoConvert_diki_ComplianceRunList_To_v1alpha1_ComplianceRunList(in, out, s)
}

func autoConvert_v1alpha1_ComplianceRunSpec_To_diki_ComplianceRunSpec(in *ComplianceRunSpec, out *diki.ComplianceRunSpec, s conversion.Scope) error {
	out.Rulesets = *(*[]diki.RulesetConfig)(unsafe.Pointer(&in.Rulesets))
	return nil
}

// Convert_v1alpha1_ComplianceRunSpec_To_diki_ComplianceRunSpec is an autogenerated conversion function.
func Convert_v1alpha1_ComplianceRunSpec_To_diki_ComplianceRunSpec(in *ComplianceRunSpec, out *diki.ComplianceRunSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ComplianceRunSpec_To_diki_ComplianceRunSpec(in, out, s)
}

func autoConvert_diki_ComplianceRunSpec_To_v1alpha1_ComplianceRunSpec(in *diki.ComplianceRunSpec, out *ComplianceRunSpec, s conversion.Scope) error {
	out.Rulesets = *(*[]RulesetConfig)(unsafe.Pointer(&in.Rulesets))
	return nil
}

// Convert_diki_ComplianceRunSpec_To_v1alpha1_ComplianceRunSpec is an autogenerated conversion function.
func Convert_diki_ComplianceRunSpec_To_v1alpha1_ComplianceRunSpec(in *diki.ComplianceRunSpec, out *ComplianceRunSpec, s conversion.Scope) error {
	return autoConvert_diki_ComplianceRunSpec_To_v1alpha1_ComplianceRunSpec(in, out, s)
}

func autoConvert_v1alpha1_ComplianceRunStatus_To_diki_ComplianceRunStatus(in *ComplianceRunStatus, out *diki.ComplianceRunStatus, s conversion.Scope) error {
	out.Conditions = *(*[]diki.Condition)(unsafe.Pointer(&in.Conditions))
	out.Phase = diki.ComplianceRunPhase(in.Phase)
	out.Rulesets = *(*[]diki.RulesetSummary)(unsafe.Pointer(&in.Rulesets))
	return nil
}

// Convert_v1alpha1_ComplianceRunStatus_To_diki_ComplianceRunStatus is an autogenerated conversion function.
func Convert_v1alpha1_ComplianceRunStatus_To_diki_ComplianceRunStatus(in *ComplianceRunStatus, out *diki.ComplianceRunStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_ComplianceRunStatus_To_diki_ComplianceRunStatus(in, out, s)
}

func autoConvert_diki_ComplianceRunStatus_To_v1alpha1_ComplianceRunStatus(in *diki.ComplianceRunStatus, out *ComplianceRunStatus, s conversion.Scope) error {
	out.Conditions = *(*[]Condition)(unsafe.Pointer(&in.Conditions))
	out.Phase = ComplianceRunPhase(in.Phase)
	out.Rulesets = *(*[]RulesetSummary)(unsafe.Pointer(&in.Rulesets))
	return nil
}

// Convert_diki_ComplianceRunStatus_To_v1alpha1_ComplianceRunStatus is an autogenerated conversion function.
func Convert_diki_ComplianceRunStatus_To_v1alpha1_ComplianceRunStatus(in *diki.ComplianceRunStatus, out *ComplianceRunStatus, s conversion.Scope) error {
	return autoConvert_diki_ComplianceRunStatus_To_v1alpha1_ComplianceRunStatus(in, out, s)
}

func autoConvert_v1alpha1_Condition_To_diki_Condition(in *Condition, out *diki.Condition, s conversion.Scope) error {
	out.Type = diki.ConditionType(in.Type)
	out.Status = diki.ConditionStatus(in.Status)
	out.LastUpdateTime = in.LastUpdateTime
	out.LastTransitionTime = in.LastTransitionTime
	out.Reason = in.Reason
	out.Message = in.Message
	return nil
}

// Convert_v1alpha1_Condition_To_diki_Condition is an autogenerated conversion function.
func Convert_v1alpha1_Condition_To_diki_Condition(in *Condition, out *diki.Condition, s conversion.Scope) error {
	return autoConvert_v1alpha1_Condition_To_diki_Condition(in, out, s)
}

func autoConvert_diki_Condition_To_v1alpha1_Condition(in *diki.Condition, out *Condition, s conversion.Scope) error {
	out.Type = ConditionType(in.Type)
	out.Status = ConditionStatus(in.Status)
	out.LastUpdateTime = in.LastUpdateTime
	out.LastTransitionTime = in.LastTransitionTime
	out.Reason = in.Reason
	out.Message = in.Message
	return nil
}

// Convert_diki_Condition_To_v1alpha1_Condition is an autogenerated conversion function.
func Convert_diki_Condition_To_v1alpha1_Condition(in *diki.Condition, out *Condition, s conversion.Scope) error {
	return autoConvert_diki_Condition_To_v1alpha1_Condition(in, out, s)
}

func autoConvert_v1alpha1_Options_To_diki_Options(in *Options, out *diki.Options, s conversion.Scope) error {
	out.ConfigMapRef = (*diki.OptionsConfigMapRef)(unsafe.Pointer(in.ConfigMapRef))
	return nil
}

// Convert_v1alpha1_Options_To_diki_Options is an autogenerated conversion function.
func Convert_v1alpha1_Options_To_diki_Options(in *Options, out *diki.Options, s conversion.Scope) error {
	return autoConvert_v1alpha1_Options_To_diki_Options(in, out, s)
}

func autoConvert_diki_Options_To_v1alpha1_Options(in *diki.Options, out *Options, s conversion.Scope) error {
	out.ConfigMapRef = (*OptionsConfigMapRef)(unsafe.Pointer(in.ConfigMapRef))
	return nil
}

// Convert_diki_Options_To_v1alpha1_Options is an autogenerated conversion function.
func Convert_diki_Options_To_v1alpha1_Options(in *diki.Options, out *Options, s conversion.Scope) error {
	return autoConvert_diki_Options_To_v1alpha1_Options(in, out, s)
}

func autoConvert_v1alpha1_OptionsConfigMapRef_To_diki_OptionsConfigMapRef(in *OptionsConfigMapRef, out *diki.OptionsConfigMapRef, s conversion.Scope) error {
	out.Name = in.Name
	out.Namespace = in.Namespace
	out.Key = (*string)(unsafe.Pointer(in.Key))
	return nil
}

// Convert_v1alpha1_OptionsConfigMapRef_To_diki_OptionsConfigMapRef is an autogenerated conversion function.
func Convert_v1alpha1_OptionsConfigMapRef_To_diki_OptionsConfigMapRef(in *OptionsConfigMapRef, out *diki.OptionsConfigMapRef, s conversion.Scope) error {
	return autoConvert_v1alpha1_OptionsConfigMapRef_To_diki_OptionsConfigMapRef(in, out, s)
}

func autoConvert_diki_OptionsConfigMapRef_To_v1alpha1_OptionsConfigMapRef(in *diki.OptionsConfigMapRef, out *OptionsConfigMapRef, s conversion.Scope) error {
	out.Name = in.Name
	out.Namespace = in.Namespace
	out.Key = (*string)(unsafe.Pointer(in.Key))
	return nil
}

// Convert_diki_OptionsConfigMapRef_To_v1alpha1_OptionsConfigMapRef is an autogenerated conversion function.
func Convert_diki_OptionsConfigMapRef_To_v1alpha1_OptionsConfigMapRef(in *diki.OptionsConfigMapRef, out *OptionsConfigMapRef, s conversion.Scope) error {
	return autoConvert_diki_OptionsConfigMapRef_To_v1alpha1_OptionsConfigMapRef(in, out, s)
}

func autoConvert_v1alpha1_Rule_To_diki_Rule(in *Rule, out *diki.Rule, s conversion.Scope) error {
	out.ID = in.ID
	out.Name = in.Name
	return nil
}

// Convert_v1alpha1_Rule_To_diki_Rule is an autogenerated conversion function.
func Convert_v1alpha1_Rule_To_diki_Rule(in *Rule, out *diki.Rule, s conversion.Scope) error {
	return autoConvert_v1alpha1_Rule_To_diki_Rule(in, out, s)
}

func autoConvert_diki_Rule_To_v1alpha1_Rule(in *diki.Rule, out *Rule, s conversion.Scope) error {
	out.ID = in.ID
	out.Name = in.Name
	return nil
}

// Convert_diki_Rule_To_v1alpha1_Rule is an autogenerated conversion function.
func Convert_diki_Rule_To_v1alpha1_Rule(in *diki.Rule, out *Rule, s conversion.Scope) error {
	return autoConvert_diki_Rule_To_v1alpha1_Rule(in, out, s)
}

func autoConvert_v1alpha1_RulesFindings_To_diki_RulesFindings(in *RulesFindings, out *diki.RulesFindings, s conversion.Scope) error {
	out.Failed = *(*[]diki.Rule)(unsafe.Pointer(&in.Failed))
	out.Errored = *(*[]diki.Rule)(unsafe.Pointer(&in.Errored))
	out.Warning = *(*[]diki.Rule)(unsafe.Pointer(&in.Warning))
	return nil
}

// Convert_v1alpha1_RulesFindings_To_diki_RulesFindings is an autogenerated conversion function.
func Convert_v1alpha1_RulesFindings_To_diki_RulesFindings(in *RulesFindings, out *diki.RulesFindings, s conversion.Scope) error {
	return autoConvert_v1alpha1_RulesFindings_To_diki_RulesFindings(in, out, s)
}

func autoConvert_diki_RulesFindings_To_v1alpha1_RulesFindings(in *diki.RulesFindings, out *RulesFindings, s conversion.Scope) error {
	out.Failed = *(*[]Rule)(unsafe.Pointer(&in.Failed))
	out.Errored = *(*[]Rule)(unsafe.Pointer(&in.Errored))
	out.Warning = *(*[]Rule)(unsafe.Pointer(&in.Warning))
	return nil
}

// Convert_diki_RulesFindings_To_v1alpha1_RulesFindings is an autogenerated conversion function.
func Convert_diki_RulesFindings_To_v1alpha1_RulesFindings(in *diki.RulesFindings, out *RulesFindings, s conversion.Scope) error {
	return autoConvert_diki_RulesFindings_To_v1alpha1_RulesFindings(in, out, s)
}

func autoConvert_v1alpha1_RulesResults_To_diki_RulesResults(in *RulesResults, out *diki.RulesResults, s conversion.Scope) error {
	if err := Convert_v1alpha1_RulesSummary_To_diki_RulesSummary(&in.Summary, &out.Summary, s); err != nil {
		return err
	}
	out.Rules = (*diki.RulesFindings)(unsafe.Pointer(in.Rules))
	return nil
}

// Convert_v1alpha1_RulesResults_To_diki_RulesResults is an autogenerated conversion function.
func Convert_v1alpha1_RulesResults_To_diki_RulesResults(in *RulesResults, out *diki.RulesResults, s conversion.Scope) error {
	return autoConvert_v1alpha1_RulesResults_To_diki_RulesResults(in, out, s)
}

func autoConvert_diki_RulesResults_To_v1alpha1_RulesResults(in *diki.RulesResults, out *RulesResults, s conversion.Scope) error {
	if err := Convert_diki_RulesSummary_To_v1alpha1_RulesSummary(&in.Summary, &out.Summary, s); err != nil {
		return err
	}
	out.Rules = (*RulesFindings)(unsafe.Pointer(in.Rules))
	return nil
}

// Convert_diki_RulesResults_To_v1alpha1_RulesResults is an autogenerated conversion function.
func Convert_diki_RulesResults_To_v1alpha1_RulesResults(in *diki.RulesResults, out *RulesResults, s conversion.Scope) error {
	return autoConvert_diki_RulesResults_To_v1alpha1_RulesResults(in, out, s)
}

func autoConvert_v1alpha1_RulesSummary_To_diki_RulesSummary(in *RulesSummary, out *diki.RulesSummary, s conversion.Scope) error {
	out.Passed = in.Passed
	out.Skipped = in.Skipped
	out.Accepted = in.Accepted
	out.Warning = in.Warning
	out.Failed = in.Failed
	out.Errored = in.Errored
	return nil
}

// Convert_v1alpha1_RulesSummary_To_diki_RulesSummary is an autogenerated conversion function.
func Convert_v1alpha1_RulesSummary_To_diki_RulesSummary(in *RulesSummary, out *diki.RulesSummary, s conversion.Scope) error {
	return autoConvert_v1alpha1_RulesSummary_To_diki_RulesSummary(in, out, s)
}

func autoConvert_diki_RulesSummary_To_v1alpha1_RulesSummary(in *diki.RulesSummary, out *RulesSummary, s conversion.Scope) error {
	out.Passed = in.Passed
	out.Skipped = in.Skipped
	out.Accepted = in.Accepted
	out.Warning = in.Warning
	out.Failed = in.Failed
	out.Errored = in.Errored
	return nil
}

// Convert_diki_RulesSummary_To_v1alpha1_RulesSummary is an autogenerated conversion function.
func Convert_diki_RulesSummary_To_v1alpha1_RulesSummary(in *diki.RulesSummary, out *RulesSummary, s conversion.Scope) error {
	return autoConvert_diki_RulesSummary_To_v1alpha1_RulesSummary(in, out, s)
}

func autoConvert_v1alpha1_RulesetConfig_To_diki_RulesetConfig(in *RulesetConfig, out *diki.RulesetConfig, s conversion.Scope) error {
	out.ID = in.ID
	out.Version = in.Version
	out.Options = (*diki.RulesetOptions)(unsafe.Pointer(in.Options))
	return nil
}

// Convert_v1alpha1_RulesetConfig_To_diki_RulesetConfig is an autogenerated conversion function.
func Convert_v1alpha1_RulesetConfig_To_diki_RulesetConfig(in *RulesetConfig, out *diki.RulesetConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_RulesetConfig_To_diki_RulesetConfig(in, out, s)
}

func autoConvert_diki_RulesetConfig_To_v1alpha1_RulesetConfig(in *diki.RulesetConfig, out *RulesetConfig, s conversion.Scope) error {
	out.ID = in.ID
	out.Version = in.Version
	out.Options = (*RulesetOptions)(unsafe.Pointer(in.Options))
	return nil
}

// Convert_diki_RulesetConfig_To_v1alpha1_RulesetConfig is an autogenerated conversion function.
func Convert_diki_RulesetConfig_To_v1alpha1_RulesetConfig(in *diki.RulesetConfig, out *RulesetConfig, s conversion.Scope) error {
	return autoConvert_diki_RulesetConfig_To_v1alpha1_RulesetConfig(in, out, s)
}

func autoConvert_v1alpha1_RulesetOptions_To_diki_RulesetOptions(in *RulesetOptions, out *diki.RulesetOptions, s conversion.Scope) error {
	out.Ruleset = (*diki.Options)(unsafe.Pointer(in.Ruleset))
	out.Rules = (*diki.Options)(unsafe.Pointer(in.Rules))
	return nil
}

// Convert_v1alpha1_RulesetOptions_To_diki_RulesetOptions is an autogenerated conversion function.
func Convert_v1alpha1_RulesetOptions_To_diki_RulesetOptions(in *RulesetOptions, out *diki.RulesetOptions, s conversion.Scope) error {
	return autoConvert_v1alpha1_RulesetOptions_To_diki_RulesetOptions(in, out, s)
}

func autoConvert_diki_RulesetOptions_To_v1alpha1_RulesetOptions(in *diki.RulesetOptions, out *RulesetOptions, s conversion.Scope) error {
	out.Ruleset = (*Options)(unsafe.Pointer(in.Ruleset))
	out.Rules = (*Options)(unsafe.Pointer(in.Rules))
	return nil
}

// Convert_diki_RulesetOptions_To_v1alpha1_RulesetOptions is an autogenerated conversion function.
func Convert_diki_RulesetOptions_To_v1alpha1_RulesetOptions(in *diki.RulesetOptions, out *RulesetOptions, s conversion.Scope) error {
	return autoConvert_diki_RulesetOptions_To_v1alpha1_RulesetOptions(in, out, s)
}

func autoConvert_v1alpha1_RulesetSummary_To_diki_RulesetSummary(in *RulesetSummary, out *diki.RulesetSummary, s conversion.Scope) error {
	out.ID = in.ID
	out.Version = in.Version
	if err := Convert_v1alpha1_RulesResults_To_diki_RulesResults(&in.Results, &out.Results, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_RulesetSummary_To_diki_RulesetSummary is an autogenerated conversion function.
func Convert_v1alpha1_RulesetSummary_To_diki_RulesetSummary(in *RulesetSummary, out *diki.RulesetSummary, s conversion.Scope) error {
	return autoConvert_v1alpha1_RulesetSummary_To_diki_RulesetSummary(in, out, s)
}

func autoConvert_diki_RulesetSummary_To_v1alpha1_RulesetSummary(in *diki.RulesetSummary, out *RulesetSummary, s conversion.Scope) error {
	out.ID = in.ID
	out.Version = in.Version
	if err := Convert_diki_RulesResults_To_v1alpha1_RulesResults(&in.Results, &out.Results, s); err != nil {
		return err
	}
	return nil
}

// Convert_diki_RulesetSummary_To_v1alpha1_RulesetSummary is an autogenerated conversion function.
func Convert_diki_RulesetSummary_To_v1alpha1_RulesetSummary(in *diki.RulesetSummary, out *RulesetSummary, s conversion.Scope) error {
	return autoConvert_diki_RulesetSummary_To_v1alpha1_RulesetSummary(in, out, s)
}
