//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComplianceRun) DeepCopyInto(out *ComplianceRun) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComplianceRun.
func (in *ComplianceRun) DeepCopy() *ComplianceRun {
	if in == nil {
		return nil
	}
	out := new(ComplianceRun)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ComplianceRun) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComplianceRunList) DeepCopyInto(out *ComplianceRunList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ComplianceRun, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComplianceRunList.
func (in *ComplianceRunList) DeepCopy() *ComplianceRunList {
	if in == nil {
		return nil
	}
	out := new(ComplianceRunList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ComplianceRunList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComplianceRunSpec) DeepCopyInto(out *ComplianceRunSpec) {
	*out = *in
	if in.Rulesets != nil {
		in, out := &in.Rulesets, &out.Rulesets
		*out = make([]RulesetConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComplianceRunSpec.
func (in *ComplianceRunSpec) DeepCopy() *ComplianceRunSpec {
	if in == nil {
		return nil
	}
	out := new(ComplianceRunSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComplianceRunStatus) DeepCopyInto(out *ComplianceRunStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Rulesets != nil {
		in, out := &in.Rulesets, &out.Rulesets
		*out = make([]RulesetSummary, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComplianceRunStatus.
func (in *ComplianceRunStatus) DeepCopy() *ComplianceRunStatus {
	if in == nil {
		return nil
	}
	out := new(ComplianceRunStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Condition) DeepCopyInto(out *Condition) {
	*out = *in
	in.LastUpdateTime.DeepCopyInto(&out.LastUpdateTime)
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Condition.
func (in *Condition) DeepCopy() *Condition {
	if in == nil {
		return nil
	}
	out := new(Condition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Options) DeepCopyInto(out *Options) {
	*out = *in
	if in.ConfigMapRef != nil {
		in, out := &in.ConfigMapRef, &out.ConfigMapRef
		*out = new(OptionsConfigMapRef)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Options.
func (in *Options) DeepCopy() *Options {
	if in == nil {
		return nil
	}
	out := new(Options)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OptionsConfigMapRef) DeepCopyInto(out *OptionsConfigMapRef) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OptionsConfigMapRef.
func (in *OptionsConfigMapRef) DeepCopy() *OptionsConfigMapRef {
	if in == nil {
		return nil
	}
	out := new(OptionsConfigMapRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Rule) DeepCopyInto(out *Rule) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Rule.
func (in *Rule) DeepCopy() *Rule {
	if in == nil {
		return nil
	}
	out := new(Rule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RulesFindings) DeepCopyInto(out *RulesFindings) {
	*out = *in
	if in.Failed != nil {
		in, out := &in.Failed, &out.Failed
		*out = make([]Rule, len(*in))
		copy(*out, *in)
	}
	if in.Errored != nil {
		in, out := &in.Errored, &out.Errored
		*out = make([]Rule, len(*in))
		copy(*out, *in)
	}
	if in.Warning != nil {
		in, out := &in.Warning, &out.Warning
		*out = make([]Rule, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RulesFindings.
func (in *RulesFindings) DeepCopy() *RulesFindings {
	if in == nil {
		return nil
	}
	out := new(RulesFindings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RulesResults) DeepCopyInto(out *RulesResults) {
	*out = *in
	out.Summary = in.Summary
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = new(RulesFindings)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RulesResults.
func (in *RulesResults) DeepCopy() *RulesResults {
	if in == nil {
		return nil
	}
	out := new(RulesResults)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RulesSummary) DeepCopyInto(out *RulesSummary) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RulesSummary.
func (in *RulesSummary) DeepCopy() *RulesSummary {
	if in == nil {
		return nil
	}
	out := new(RulesSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RulesetConfig) DeepCopyInto(out *RulesetConfig) {
	*out = *in
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = new(RulesetOptions)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RulesetConfig.
func (in *RulesetConfig) DeepCopy() *RulesetConfig {
	if in == nil {
		return nil
	}
	out := new(RulesetConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RulesetOptions) DeepCopyInto(out *RulesetOptions) {
	*out = *in
	if in.Ruleset != nil {
		in, out := &in.Ruleset, &out.Ruleset
		*out = new(Options)
		(*in).DeepCopyInto(*out)
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = new(Options)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RulesetOptions.
func (in *RulesetOptions) DeepCopy() *RulesetOptions {
	if in == nil {
		return nil
	}
	out := new(RulesetOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RulesetSummary) DeepCopyInto(out *RulesetSummary) {
	*out = *in
	in.Results.DeepCopyInto(&out.Results)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RulesetSummary.
func (in *RulesetSummary) DeepCopy() *RulesetSummary {
	if in == nil {
		return nil
	}
	out := new(RulesetSummary)
	in.DeepCopyInto(out)
	return out
}
